apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftegan-app
  namespace: dev
  labels:
    app: ftegan-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftegan-app
  template:
    metadata:
      labels:
        app: ftegan-app
    spec:
      containers:
      - name: ftegan-app
        image: aidarngdev/ftegan:v2
        ports:
        - containerPort: 8888
